### ISSUE TITLE
Nicer API

### ISSUE THREAD

**Issue by daurnimator** [arcapos/luapgsql#13]
Continuing from https://github.com/mbalmer/luapgsql/pull/6#issuecomment-67770765

> One other API changing modification to make is around return values. There are functions that return 0 or 1, or -1 and 0. Using actual booleans would make sense.

e.g.
  - `conn_flush`
  - `conn_sendQuery`
  - `conn_sendQueryParams`
  - `conn_sendPrepare`
  - `conn_sendQueryPrepared`
  - `conn_sendDescribePrepared`
  - `conn_sendDescribePortal`
  - `conn_setSingleRowMode`

**Comment by daurnimator** [comment]
Thought of another one today: `PQsocket` should return `nil` instead of `-1` when the fd is invalid.

**Comment by mbalmer** [comment]
I am starting to work on this.  This will break compatability with earlier versions, though. So be careful with luapgsql versions 1.5 an higher once they show up here.

**Comment by mbalmer** [comment]
A corresponding change has been committed, but I did not yet make new release.

**Comment by daurnimator** [comment]
Please also update `resetStart` and `resetPoll`

**Comment by mbalmer** [comment]
> Am 12.05.2016 um 03:57 schrieb daurnimator <notifications@github.com>:
> 
> Please also update resetStart and resetPoll
> 
> 
done.

**Comment by daurnimator** [comment]
> > Please also update resetStart and resetPoll
> done.

Sorry, `resetPoll` shoudn't have been changed (just `resetStart`). I edited my comment after but I guess that doesn't send an email notification.
