### ISSUE TITLE
setNoticeReceiver + setNoticeProcessor should return the previous function

### ISSUE THREAD

**Issue by daurnimator** [arcapos/luapgsql#15]
http://www.postgresql.org/docs/current/static/libpq-notice-processing.html

> Each of these functions returns the previous notice receiver or processor function pointer, and sets the new value. If you supply a null function pointer, no action is taken, but the current pointer is returned.

**Comment by mbalmer** [comment]
This won't work easily, since a wrapper function gets installed that calls a Lua function. I wonder if it's worth the effort to make it 100% compatible to libpq here.  To you use this feature?

**Comment by daurnimator** [comment]
I was thinking you'd just return the previous value of (e.g.) `__pgsqlNoticeReceiver`
As luapgsql 'owns' the `PGConn` object; you probably can assume that the notice receiver will always be yours...

**Comment by mbalmer** [comment]
I think this can well be dealt with in Lua itself.
