### ISSUE TITLE
NoticeProcessor and NoticeReceiver are global

### ISSUE THREAD

**Issue by daurnimator** [arcapos/luapgsql#25]
`setNoticeProcessor` and `setNoticeReceiver` set themselves in a global context; meaning all PGconns in one lua state end up sharing the same callbacks. This isn't acceptable for libraries that use luapgsql underneath.

**Comment by daurnimator** [comment]
The commit 38b8e845ab07ad003e06b144e6f03c0e4fd851da should help fix things up by providing a place to store the lua functions.

**Comment by daurnimator** [comment]
@mbalmer can we solve this soon?

**Comment by mbalmer** [comment]
I have just commited a new version that make noticeReceiver and noticeProcessor per connection and added a sample program in notice.lua.
