### ISSUE TITLE
Potential leak in encryptPassword

### ISSUE THREAD

**Issue by daurnimator** [arcapos/luapgsql#26]
`lua_pushstring` can throw, which will result in `PQfreemem(encrypted);` never getting called.
https://github.com/arcapos/luapgsql/blob/328f6cb89b588775be8a598bb86040fd2fa0a4ac/luapgsql.c#L136

Same issue in [`conn_escapeString`](https://github.com/arcapos/luapgsql/blob/328f6cb89b588775be8a598bb86040fd2fa0a4ac/luapgsql.c#L678), [`conn_escapeLiteral`](https://github.com/arcapos/luapgsql/blob/328f6cb89b588775be8a598bb86040fd2fa0a4ac/luapgsql.c#L707), `conn_escapeIdentifier`, `conn_escapeBytea`, `conn_unescapeBytea`, `conn_getCopyData`

Similar issue in [`conn_cancel`](https://github.com/arcapos/luapgsql/blob/328f6cb89b588775be8a598bb86040fd2fa0a4ac/luapgsql.c#L986)

**Comment by mbalmer** [comment]
What extactly do you mean by "can throw"?  What will happen in such a case (which, btw, is not documented), will it call err() or exit()?  Or longjmp() (where to?)

**Comment by daurnimator** [comment]
> What extactly do you mean by "can throw"? What will happen in such a case (which, btw, is not documented), will it call err() or exit()? Or longjmp() (where to?)

"can throw" in the lua C API means "can `longjmp` out"

It is documented in the lua manual: [`lua_pushstring`](http://www.lua.org/manual/5.3/manual.html#lua_pushstring) is annotated with 'm', which (as mentioned in section 4.8) means: "the function may raise memory errors".

-----------------------

One solution is to set up garbage collection on the to-be-freed string:

```C
static int
pgsql_encryptPassword(lua_State *L)
{
	char *encrypted;

        const char* str = luaL_checkstring(L, 1);
        const char* 

	encrypted = PQencryptPassword(
	    luaL_checkstring(L, 2));
	if (encrypted != NULL) {
		lua_pushstring(L, encrypted);
		PQfreemem(encrypted);
	} else
		lua_pushnil(L);
	return 1;
}
```

**Comment by daurnimator** [comment]
sorry, I clicked send before finishing the comment/code. edited on github.

**Comment by mbalmer** [comment]
Not sure if it is really worth going that far for every small allocation. Especially since the default behaviour of Lua is to terminate the calling program in case of an error anyways.

**Comment by daurnimator** [comment]
> Especially since the default behaviour of Lua is to terminate the calling program in case of an error anyways.

Not it's not... It goes up to the nearest `pcall`.

**Comment by mbalmer** [comment]
I still think this is cluttering the code for no real gain.  Do such memory errors happen in real live or are we trying to fix a hypothetical problem here?

**Comment by daurnimator** [comment]
> I still think this is cluttering the code for no real gain. Do such memory errors happen in real live or are we trying to fix a hypothetical problem here?

It's as likely as `malloc` failing. i.e. it depends on your operating system, how it's configured and your libc.
When I have a memory leak in my lua programs I often have few options other than to go through all the C libraries we use to look for culprits. In this case: I found several in luapgsql.

**Comment by mbalmer** [comment]
I could think of a set of small, reusable functions, this adds a little overhead, but the code remains readable:

```
/*
 * Garbage collected memory
 */
static void **
gcmalloc(lua_State *L, size_t size)
{
	void **p;
	p = lua_newuserdata(L, size);
	*p = NULL;
	luaL_setmetatable(L, GCMEM_METATABLE);
	return p;
}

/* Memory can be free'ed immediately or left to the garbage collector */
static void
gcfree(void **p)
{
	PQfreemem(*p);
	*p = NULL;
}

static int
gcmem_clear(lua_State *L)
{
	void **p = luaL_checkudata(L, 1, GCMEM_METATABLE);
	PQfreemem(*p);
	*p = NULL;
	return 0;
}
```

Then later use them like you sugegsted:

```
static int
pgsql_encryptPassword(lua_State *L)
{
	void **pw;

	pw = gcmalloc(L, sizeof(char *));
	*pw = PQencryptPassword(luaL_checkstring(L, 1), luaL_checkstring(L, 2));
	lua_pushstring(L, *pw);
	gcfree(pw);
	return 1;
}
```

Note that the call to `gcfree()` is purely optional, but it's probably a good think to immediately free memory if we can.

**Comment by siffiejoe** [comment]
I have [used a similar set of helper functions][1], and I think that not handling memory allocation errors is definitely a code-smell -- especially since the Lua team [goes to great lengths][2] to ensure that Lua itself does the right thing when `malloc` fails. This effort is wasted if some extension module author chooses not to bother.

  [1]:  http://lua-users.org/lists/lua-l/2016-03/msg00002.html
  [2]:  http://lua-users.org/lists/lua-l/2008-10/msg00379.html

**Comment by mbalmer** [comment]
So you suggest to try to replace all occurences of malloc etc. by lua_newuserdata, to make every allocation, and be it small, garbage collectable ?

**Comment by siffiejoe** [comment]
Yes. The only exception I can think of is as part of another finalizable userdata.

You can add stack-based allocations for small memory chunks as an optimization later if necessary (which I doubt will be the case):

```C
char buffer[ REASONABLE_SIZE ];
char* ptr = buffer;
if( n > sizeof( buffer ) )
  ptr = lua_newuserdata( L, n );
/* use ptr */
```

(This is pretty much equivalent to using the `luaL_Buffer` API as Tomas suggested on lua-l.)

**Comment by mbalmer** [comment]
This issue has now been fixed.  It uses the mechanism daurnimator suggested (factored out in some small functions, so it can be easily reused(.
