### ISSUE TITLE
Potential leaks due to delayed argument checking

### ISSUE THREAD

**Issue by daurnimator** [arcapos/luapgsql#28]
e.g. in [conn_sendQueryParams](https://github.com/arcapos/luapgsql/blob/328f6cb89b588775be8a598bb86040fd2fa0a4ac/luapgsql.c#L784)

If the first argument is not a pgsql connection, then it will throw at [line 821](https://github.com/arcapos/luapgsql/blob/328f6cb89b588775be8a598bb86040fd2fa0a4ac/luapgsql.c#L821). However at this point `paramTypes`, `paramValues`, etc have already been allocated.

Fix is to move those arguments check to the start of the function.

Same issue is in other places, including `conn_execParams`, `conn_prepare`, `conn_execPrepared`, `conn_sendPrepare`, `conn_sendQueryPrepared`,

**Comment by mbalmer** [comment]
Right.  I moved the check for the connection object to the top of these functions (although the memory would not leak anymore due to the use of lua_newuserdata().  Thanks!

**Comment by daurnimator** [comment]
This matters for more than just the connection object.
You should also move up the other argument checking (like `luaL_checkstring`).

**Comment by daurnimator** [comment]
> You should also move up the other argument checking (like luaL_checkstring).

This was fixed in 252104788ee25610cad77abdd87ca4538865b54e
