### ISSUE TITLE
use luaL_testudata instead of luaL_checkudata in cleanups

### ISSUE THREAD

**Issue by daurnimator** [arcapos/luapgsql#29]
[`res_clear`](https://github.com/arcapos/luapgsql/blob/328f6cb89b588775be8a598bb86040fd2fa0a4ac/luapgsql.c#L1683) should probably have used `testudata` instead of `checkudata`

Same with [`conn_finish`](https://github.com/arcapos/luapgsql/blob/328f6cb89b588775be8a598bb86040fd2fa0a4ac/luapgsql.c#L155), [`notify_clear`](https://github.com/arcapos/luapgsql/blob/328f6cb89b588775be8a598bb86040fd2fa0a4ac/luapgsql.c#L1729), [`pgsql_lo_clear`](https://github.com/arcapos/luapgsql/blob/328f6cb89b588775be8a598bb86040fd2fa0a4ac/luapgsql.c#L1812)

**Comment by mbalmer** [comment]
How would res_clear() end up being called not by resultset?  I don't agree that this is an issue.

**Comment by mbalmer** [comment]
I leave this out for now, as luaL_testudata is not available in Lua 5.1.  Also, I don't think these functions will be called other than for __gc purposes.

**Comment by daurnimator** [comment]
>  I don't think these functions will be called other than for __gc purposes.

`conn_finish` is the main exception here.
