### ISSUE TITLE
PQputCopyEnd errormsg argument

### ISSUE THREAD

**Issue by daurnimator** [arcapos/luapgsql#41]
> `int PQputCopyEnd(PGconn *conn, const char *errormsg);`
> Ends the COPY_IN operation successfully if errormsg is NULL. If errormsg is not NULL then the COPY is forced to fail, with the string pointed to by errormsg used as the error message. (One should not assume that this exact error message will come back from the server, however, as the server might have already failed the COPY for its own reasons. Also note that the option to force failure does not work when using pre-3.0-protocol connections.)

To fail a copy you need to be able to pass an `errormsg`

**Comment by mbalmer** [comment]
This is now fixed in -head.  Thanks.
