### ISSUE TITLE
Expose res_clear as method

### ISSUE THREAD

**Issue by daurnimator** [arcapos/luapgsql#42]
To allow explicit collection, please expose `res_clear` (currently a __gc metamethod) as `res:clear()`

**Comment by mbalmer** [comment]
> Am 12.09.2016 um 03:18 schrieb daurnimator <notifications@github.com>:
> 
> To allow explicit collection, please expose res_clear (currently a __gc metamethod) as res:clear()
> 
> 

Easy enough to add, but why do you want that?  What is the reason?  The
automatic gc worksed fine for me, even with very large results.

(not objecting, jusr asking)

**Comment by daurnimator** [comment]
I was converting some C code (that used libpq) to lua. It would be nice for debuggability if I can make the calls into libpq deterministic.

**Comment by mbalmer** [comment]
I will soon add methamethods to make result sets <close>-able.  Think that is the proper way.

**Comment by daurnimator** [comment]
This issue was about exposing the method as more than a metamethod, so that I could call it e.g. in a test exactly when I wanted.
Rather than waiting for the GC; or with lua 5.4's new close: ending the current scope.

Please consider reopening/accepting?

**Comment by mbalmer** [comment]
If you can make use of this feature, then I can add it, it does not harm.

So yes, I will add it.
