### ISSUE TITLE
res_oidValue should push nil on InvalidOid

### ISSUE THREAD

**Issue by daurnimator** [arcapos/luapgsql#43]

**Comment by mbalmer** [comment]
Why do you want this?  InvalidOid is zero (0), so it's perfectly distinguishable already.

**Comment by daurnimator** [comment]
> InvalidOid is zero (0),

That's not exposed anywhere, and I don't know if it should be?

`res_oidValue` returns `InvalidOid` when the question didn't make sense and no data is available: this sort of thing maps well to the semantics of lua nil

**Comment by mbalmer** [comment]
If it was exposed as pgsql.InvalidOid then the (C) code would stay small and lean.  And an if is needed in Lua anyway to check the result.

I think I’d slight prefer to expose that symbol (it’s also defined in the C header files)

**Comment by mbalmer** [comment]
For the time being, I defined pgsql.InvalidOid (the value, btw, is documented)

**Comment by mbalmer** [comment]
InvalidOid has the documented value of zero, so returning this allows you detect an invalid OID.  To make thinks clearer I exposed the value as pgsql.InvalidOid.
