### ISSUE TITLE
escapeBytea: use pushlstring

### ISSUE THREAD

**Issue by daurnimator** [arcapos/luapgsql#50]
Should use pushlstring to save a `strlen`.

Also, I'm curious why you return the length as a 2nd return at all?

**Comment by mbalmer** [comment]
Right.  It should just pushlstring and leave out the second return, there is the length operator after all...  Then I think the value returned as second return is wrong anyway, as per the libpq documentation it includes the trailing '\0'.  So it should do lua_pushlstring(L, *p, to_length -1).

**Comment by mbalmer** [comment]
This is fixed in the head branch.  Thanks for bringing it to my attention.
