### ISSUE TITLE
Documentation: conninfo structure?

### ISSUE THREAD

**Issue by d9k** [arcapos/luapgsql#53]
`luapgsql.adoc`:

> connectdb(conninfo) -- ... This function opens a new database connection using the parameters taken from the string conninfo.

It's unclear whether `conninfo` is structure or string. If it only may be the string please rename it to `connectionString`. And provide some usage examples please.

**Comment by mbalmer** [comment]
The Documentation says it's a string.  The wording is taken from the libpq documentation.

As for examples, take a look at the various .lua files.

**Comment by d9k** [comment]
@mbalmer, ok, it's a URI string

Example:
`'postgresql://test:123@127.0.0.1:5437/testdb'`

**Comment by daurnimator** [comment]
> @mbalmer, ok, it's a URI string

It can be.

https://www.postgresql.org/docs/current/static/libpq-connect.html#LIBPQ-CONNSTRING
It could also be a string containing whitespace separated key=value pairs like `host=localhost port=5432 dbname=mydb connect_timeout=10`

**Comment by d9k** [comment]
@mbalmer, thanks! It would be great for novice users to know about connection string types from luapgsql documentation
