### ISSUE TITLE
Featch query result as associative array?

### ISSUE THREAD

**Issue by d9k** [arcapos/luapgsql#54]
Is it possible to present query result row as associative array, where key is column name and value is column value for current row?

see http://php.net/manual/en/function.pg-fetch-assoc.php
and http://norman.github.io/lua-postgres/modules/postgres.result.html#fetch_assoc

**Comment by daurnimator** [comment]
`tuple:copy()` does this. It's not documented though.

**Comment by d9k** [comment]
@daurnimator, thanks!
@mbalmer, please improve the docs regarding this method.

**Comment by mbalmer** [comment]
Keep an eye on https://lua.msys.ch/lua-module-reference.html#pgsql, I will add the tuple:copy() function there.  Probably in a section "Lua specific functions".
