### ISSUE TITLE
Named parameters in query

### ISSUE THREAD

**Issue by d9k** [arcapos/luapgsql#55]
(for readability)

see https://github.com/brianc/node-postgres/issues/268

**Comment by daurnimator** [comment]
This is tremendously hard to get correct. Postgres does *not* support this. @mbalmer  recommend closing as wontfix

**Comment by d9k** [comment]
@daurnimator, to do it right we need to parse postgresql query to syntax tree and there are some ways to do it:

https://wiki.postgresql.org/wiki/Query_Parsing

I agree that it's an advanced functionality beyond the purpose of luapgsql library

**Comment by d9k** [comment]
@daurnimator, @mbalmer, but php has named arguments support in pdo statements for many years.
http://php.net/manual/en/pdo.prepared-statements.php

Or is their solution lack reliability too?

**Comment by daurnimator** [comment]
> Or is their solution lack reliability too?

Correct. To use the named parameters, PDO emulates prepared statements client side. This uses their general SQL parser `pdo_parse_params`, which doesn't understand all postgres statements.

**Comment by mbalmer** [comment]
As daurnimator recommends, we won't do this.
