### ISSUE TITLE
Lua 5.4 compatibility (on LuaRocks)

### ISSUE THREAD

**Issue by mna** [arcapos/luapgsql#58]
Hello,

I don't see the luarocks rockspec file in the repo, but given that it was uploaded on luarocks by one of the contributors, I assume it is under your control. Currently, the luarocks manifest has a Lua < 5.4 constraint, but as far as I can tell (having used it on a couple of my projects with Lua 5.4), it works fine with the new version. The test files in the repo also execute properly. Would it be possible to upload a new version to luarocks with support for 5.4?

Thanks,
Martin

**Comment by mbalmer** [comment]
Hi Martin

> I don't see the luarocks rockspec file in the repo, but given that it was uploaded on luarocks by one of the contributors, I assume it is under your control. Currently, the luarocks manifest has a Lua < 5.4 constraint, but as far as I can tell (having used it on a couple of my projects with Lua 5.4), it works fine with the new version. The test files in the repo also execute properly. Would it be possible to upload a new version to luarocks with support for 5.4?
> 

The rockspecs are in a separate repository at https://github.com/arcapos/rockspecs <https://github.com/arcapos/rockspecs>, the idea once was that Pierre Chapuis would maintain them, as we don't use rockspecs (we package your Lua modules as debian and rpm packages for various Linux distros, i.e. we have you own Lua distro plus modules, that way we are not dependend on the Lua being distributed by the distro maintainers).

You'd be more than welcome to create merge request for the rockspecks, of course.

As for luapgsql we have foreseen to make it more Lua 5.4 friendly, especially adding "<close>" metamethods, we think that PostgreSQL result sets could profit from this mechanism.

Sorry for the late reply, but we are super busy maintaining our software.

**Comment by mna** [comment]
Hello Marc,

> The rockspecs are in a separate repository at

Perfect, I hadn't noticed that, I'll send a patch there.

> As for luapgsql we have foreseen to make it more Lua 5.4 friendly, especially adding "<close>" metamethods

Yeah that makes a lot of sense.

> Sorry for the late reply, but we are super busy maintaining our software.

No worries, thanks!
Martin

**Comment by mbalmer** [comment]
I already added it there. Thanks for contributing it.

**Comment by mna** [comment]
Hello Marc,

I may have misunderstood your last comment, but I took it to mean you had already added the 5.4 support in the luapgsql rockspec, however I don't see it in the rockspecs repository, nor on luarocks? Would you like me to send the patch after all?

Thanks,
Martin

**Comment by mbalmer** [comment]
Yes of course, please
