### ISSUE TITLE
Lua 5.2 support

### ISSUE THREAD

**Issue by drTr0jan** [arcapos/luapgsql#60]
There's a regression after https://github.com/arcapos/luapgsql/commit/1d9ffb635a6161aebc97ab19bd890a0029b030de

`lua_getfield()` should return `void` in Lua < 5.3.

**Comment by mbalmer** [comment]
I think the right way to deal with this situation is to drop support for old Lua versions altogether. Lua is easy to upgrade.Am 18.08.2023 um 17:22 schrieb Boris Korzune ***@***.***>:﻿
There's a regression after 1d9ffb6
lua_getfield() should return void in Lua < 5.3.

**Comment by drTr0jan** [comment]
@mbalmer, I think it's good idea to specify supported Lua versions in Readme, isn't it?
Thx!

**Comment by mbalmer** [comment]
That, or someone who still uses 5.2 may propose a proper pull request with #ifdefs?Am 19.08.2023 um 15:11 schrieb Boris Korzun ***@***.***>:﻿
@mbalmer, I think it's good idea to specify supported Lua versions in Readme, isn't it?
Thx!
